languageCode =  "en-us"
title =  "Abid's Portfolio"
theme =  "toha"

# Enable Google Analytics
googleAnalytics = "G-PQMV6SF4ML"

# Manage languages
# For any more details, you can check the official documentation: https://gohugo.io/content-management/multilingual/
enableEmoji = true

[languages.en]
languageName = "English"
weight = 1

[markup.tableOfContents]
startLevel = 2
endLevel = 6
ordered = true

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
gitRepo = "https://github.com/abid/abid.github.io"
gitBranch = "main"
enableBlogPost = false
enableTOC = true
background= "images/wp2672841.jpg"

  [params.newsletter]
  enable = false
  provider = "mailchimp"
  mailchimpURL = "https://github.us1.list-manage.com/subscribe/post?u=19de52a4603135aae97163fd8&amp;id=094a24c76e"

  [params.logo]
  main = "images/Abz.svg"
  inverted = "images/Abz.svg"
  favicon = "images/Abz-favicon.png"

[markup.goldmark.renderer]
unsafe = true


[footer]
enable = true
template = "footer.html"

  [footer.navigation]
  enable = true

  [footer.contactMe]
  enable = true

  [footer.credentials]
  enable = true

  [footer.newsletter]
  enable = false
  provider = "mailchimp"
  mailchimpURL = "https://github.us1.list-manage.com/subscribe/post?u=19de52a4603135aae97163fd8&amp;id=094a24c76e"

  [footer.disclaimer]
  enable = true


